### ISSUE TITLE
API Initialization Issue

### ISSUE THREAD

**Issue by VEDANTBISHT** [entbappy/End-to-end-Medical-Chatbot-using-Llama2#1]
After running the code from store_index.py file 

pinecone.init(api_key=PINECONE_API_KEY,
              environment=PINECONE_API_ENV)
              
  It shows the given error:-
  
Traceback (most recent call last):
  File "C:\Users\vedan\Downloads\kuch bhi\End-to-end-Medical-Chatbot-using-Llama2\store_index.py", line 21, in <module>
    pinecone.init(api_key=PINECONE_API_KEY,
  File "C:\Users\vedan\AppData\Roaming\Python\Python312\site-packages\pinecone\deprecation_warnings.py", line 38, in init
    raise AttributeError(msg)
AttributeError: init is no longer a top-level attribute of the pinecone package.

Please create an instance of the Pinecone class instead.

Example:

    import os
    from pinecone import Pinecone, ServerlessSpec

    pc = Pinecone(
        api_key=os.environ.get("PINECONE_API_KEY")
    )

    # Now do stuff
    if 'my_index' not in pc.list_indexes().names():
        pc.create_index(
            name='my_index',
            dimension=1536,
            metric='euclidean',
            spec=ServerlessSpec(
                cloud='aws',
                region='us-west-2'
            )
        )
        
        
  Can you pls help me find the error as init is no longer supported by Pinecone.

**Comment by smriti217** [comment]
Is it working now?

**Comment by dkk3675** [comment]
@VEDANTBISHT  I was facing the same issue. After debugging for much time, got to know that pinecone-client version <=2.2.4 only supports init package and is deprecated in furthur releases. [Ref. : [Pinecone-Migration-Guide](https://canyon-quilt-082.notion.site/Pinecone-Python-SDK-v3-0-0-Migration-Guide-056d3897d7634bf7be399676a4757c7b)]

**Comment by TenzinNsut** [comment]
`# Uninstall the new version of pinecone 
pip uninstall pinecone-client

# Now install pinecone version: 2.2.4
pip install pinecone-client==2.2.4
`

**Comment by nortln** [comment]
I reduced to a lower version but after that there was no more environment variable on the pinecone website and when I tried using chromadb it didn't work, especially with the hugging face embeddings I have been trying to solve this but to no avail. Does anyone have a fix

**Comment by d-pamneja** [comment]
I encountered the same issue, this can be tackled as follows. 

Since `__init__` is no longer a top-level attribute of the pinecone package, we will have to create an instance of pinecone via the pinecone library itself as follows. 

```python
from pinecone import Pinecone

# Creating a Pinecone instance
pc = Pinecone(api_key = os.environ["PINECONE_API_KEY"], environment = os.environ["PINECONE_API_ENV"])


index_name = "XYZ"
```

Now, when you would try to add the text chunks to the given index, it would again throw an error saying `list_indexes()` are no longer a top-level attribute of the pinecone package, as the `from_texts()` method would try to use this functionality and throw an error. To work around that, we will have to import Pinecone again, but this time using the langchain_pinecone library. The same can be seen as shown below:

 
<img width="1204" alt="Screenshot 2024-04-16 at 7 35 08 AM" src="https://github.com/entbappy/End-to-end-Medical-Chatbot-using-Llama2/assets/100751844/22e03f28-edbc-498d-9253-07a6fd9a2d3d">

**Comment by bhaveshk22** [comment]
Just follow the Quickstart guide, everything is there. Methods used to access Pinecone has changed overtime so you need to adapt the code accordingly.

**Comment by Shashank1202** [comment]
Hey, Can you solve this error with the currect version itself.

Follow this steps :

1. Get your API_KEY from pinecone.
2. Create a new index ad initialize through the following code

```bash
index_name= "give_any_index_name_of_your_wish"

pc=Pinecone(api_key=PINECONE_API_KEY)

#creating index

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name= index_name,
        dimension= 384,
        metric= 'cosine',
        spec= ServerlessSpec(cloud= 'aws', region="us-east-1")
    )
```
```bash
index= pc.Index(index_name)
index
```
Since init method is no longer available, we can't create index in pinecone and initialize this in our python scripts.

So you need to create index Through your python script and intialize this. The above code creates index and intialize through the script itself.

Hope it helped you!!!!

Still facing Issue?? Go through this

https://github.com/Shashank1202/AI-Driven-Customer-Chatbot/blob/main/research/trails.ipynb

**Comment by Mahamadtohid** [comment]
I've uploaded the error-free source code to GitHub : [https://github.com/Mahamadtohid/medicachatbot-gen-ai-llm](javascript:void(0);)

**Comment by Mahamadtohid** [comment]
[https://github.com/Mahamadtohid/medicachatbot-gen-ai-llm](javascript:void(0);)](url)

**Comment by Mahamadtohid** [comment]
[https://github.com/Mahamadtohid/medicachatbot-gen-ai-llm](url)

**Comment by pradeepthsjain** [comment]
> Is it working now?

 what did you guys used for PINECONE_API_ENV = "" was it us-east1-aws or gcp-starter

**Comment by pradeepthsjain** [comment]
> [https://github.com/Mahamadtohid/medicachatbot-gen-ai-llm](url)

what did you guys used for PINECONE_API_ENV = "" was it us-east1-aws or gcp-starter

**Comment by pradeepthsjain** [comment]
> Hey, Can you solve this error with the currect version itself.
> 
> Follow this steps :
> 
> 1. Get your API_KEY from pinecone.
> 2. Create a new index ad initialize through the following code
> 
> ```shell
> index_name= "give_any_index_name_of_your_wish"
> 
> pc=Pinecone(api_key=PINECONE_API_KEY)
> 
> #creating index
> 
> if index_name not in pc.list_indexes().names():
>     pc.create_index(
>         name= index_name,
>         dimension= 384,
>         metric= 'cosine',
>         spec= ServerlessSpec(cloud= 'aws', region="us-east-1")
>     )
> ```
> 
> ```shell
> index= pc.Index(index_name)
> index
> ```
> 
> Since init method is no longer available, we can't create index in pinecone and initialize this in our python scripts.
> 
> So you need to create index Through your python script and intialize this. The above code creates index and intialize through the script itself.
> 
> Hope it helped you!!!!
> 
> Still facing Issue?? Go through this
> 
> https://github.com/Shashank1202/AI-Driven-Customer-Chatbot/blob/main/research/trails.ipynb

what did you guys used for PINECONE_API_ENV = "" was it us-east1-aws or gcp-starter

**Comment by pradeepthsjain** [comment]
> Just follow the Quickstart guide, everything is there. Methods used to access Pinecone has changed overtime so you need to adapt the code accordingly.

what did you guys used for PINECONE_API_ENV = "" was it us-east1-aws or gcp-starter
